apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingresspoc 
  labels:
    app.kubernetes.io/name: {{ include "ui-chart.name" . }}
    helm.sh/chart: {{ include "ui-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  tls:
    - hosts:
      - mftexplorerhelmservice.tk
      secretName: tls-secret1 
  rules:
    - host: mftexplorerhelmservice.tk 
      http:
        paths:
          - path: / 
            backend:
              serviceName: {{ include "ui-chart.fullname" . }}
              servicePort: 80 
